class main_menu:
    def print_menu(self=None):
        print()
        print("-"*50)
        print(" *** Please enter one of the following commands *** ")
        print("-"*50)
        print("> create_patient <username> <phone number> <password>")  # //TODO: implement create_patient (Part 1)
        print("-"*50)
        print("> create_caregiver <username> <name> <phone number> <password>")
        print("-"*50)
        print("> login_patient <username> <password>")  # // TODO: implement login_patient (Part 1)
        print("-"*50)
        print("> login_caregiver <username> <password>")
        print("-"*50)
        print("> search_caregiver_schedule <date(MM-DD-YYYY)>")  # // TODO: implement search_caregiver_schedule (Part 2)
        print("  -- Note: caregiver's name is useful when you cancel the appointment, please write it down --")
        print("-"*50)
        print("> reserve <caregiver username> <patient username> <vaccine> <date(MM-DD-YYYY)>")  # // TODO: implement reserve (Part 2)
        print("  -- Note: please remember your appointment ID and keep it safe, it can be used for appointment cancellation --")
        print("-"*50)
        print("> upload_availability <date(MM-DD-YYYY)>")
        print("  -- Note: please enter one date at a time; and you can only upload login account availability --")
        print("-"*50)
        print("> cancel <appointment id> <caregiver name> <appointment time(MM-DD-YYYY)>")  # // TODO: implement cancel (extra credit)
        print("-"*50)
        print("> add_doses <vaccine> <number>")
        print("-"*50)
        print("> show_appointments")  # // TODO: implement show_appointments (Part 2)
        print("-"*50)
        print("> logout")  # // TODO: implement logout (Part 2)
        print("-"*50)
        print("> Quit")
        print("-"*50)
        print()

